### ISSUE TITLE
Statistics after each iteration, an option to interrupt after every completed iteration

### ISSUE THREAD

**Issue by odiroot** [tkanmae/levmar#4]
As levmar could be working pretty hard for a long time (at least in my case) I'd really like to have a way to see what it's doing.
I mean something like a user supplied function (a callback) receiving current iteration info (number, parameters, result) so it's possible to show (or log) some statistics on the screen.
Also it would be nice to have "stop callback" similar to the function above so the user can gracefully stop the computation without losing its results.
If you don't want to implement this feature I'd try to do it myself but I'd still need a hand (where to possibly start from).

**Comment by tkanmae** [comment]
Thanks for the comment.  In order to watch progress of minimization,  I would simply wrap `levmar.levmar()` as follows.  The basic idea is that you call `levmar.levmar()` repeatedly with a small value of `maxit`.  Note that `maxit` has to be larger than 1.

``` python
def progress_watch(samplerate, func, p0, y, **kwargs):
    REASONS_FAILURE = (
        'Stop by `maxit`',
        'Singular matrix.  Restart from current `p` with increased mu',
        'No further error reduction is possible. Restart with increased mu',
    )
    success = False
    # Unfortunately `maxit` has to be larger than 2.
    kwargs.update(dict(maxit=2, full_output=True))
    # If `samplerate` is 5, then output is yielded every 5 iterations.
    if samplerate < 2: samplerate = 2

    p = p0
    for it in range(1000):
        if success: return
        output = levmar.levmar(func, p, y, **kwargs)
        if output.info[3] not in REASONS_FAILURE:
            success = True
        # Update parameters.
        p = output.p
        if it % samplerate == 0:
            yield output
```

I don't like the function signature, but it does work.  You can use `progress_watch()` to see progress of minimization:

``` python
for o in progress_watch(3, func, p0, y, args=(x,)):
    # do whatever you want with the output.
    print o.r2
```

**Comment by odiroot** [comment]
Thank you for your response.
I have to say I've thought about this kind of solution. 
Although I'm a bit worried, is calling `levmar` 10 times (chaining results)  the same as calling it one time with 10 iterations?
It's not even about performance (I'd guess there's a loss). I'm thinking rather there is more stuff (e.g. jacobian) passed between iterations than just the parameters vector. Still, I can be wrong, it's my first encounter with levmar.
