### ISSUE TITLE
_gfortran_copy_string

### ISSUE THREAD

**Issue by schlafly** [tkanmae/levmar#5]
I'm interested in trying out levmar, but I'm hitting a snag during the installation.  The problem is doubtless a config issue on my end, but I'd really appreciate a hint.

Everything builds cleanly.  However, when importing into python via:
python -c "import levmar; levmar.test()"
I get:
ImportError: ...../lib/python/levmar/_core.so: undefined symbol: _gfortran_copy_string

However, running:
ldd ~/lib/python/levmar/_core.so
suggests that gfortran should be linked:
libgfortran.so.3 => /n/sw/gcc-4.6.1/lib64/libgfortran.so.3 (0x00002af7d44a0000)

Thanks a lot.

**Comment by tkanmae** [comment]
It seems that "_gfortran_copy_string" is not included gcc-4.2 or newer but it is included in gcc4.1.  What is the version of gcc with which your Python was built?  You can see it in the startup message of your Python interpreter.

**Comment by schlafly** [comment]
Yes, looks plausible.  python is built with GCC 4.1.2 20080704 but I am building levmar stuff with stuff later than 4.3 (I had tried 4.3 and 4.6).  Is the rule that the python compiler must match the levmar compiler?

**Comment by tkanmae** [comment]
I don't know how distutils picks up toolchain to build extension modules if possible.  But I guess that the default toolchain is the one Python was built with.  If you build levmar following the instruction in README, Python will build it using gcc-4.1.2 for you.

**Comment by schlafly** [comment]
I definitely followed the instructions in the README, but as far as I can tell gcc 4.1.2 is no longer available for me to use.  I'll try to get a version of python compiled with a more recent gcc or something; thanks for the pointer.
